version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run webdriver-update
            - run: npm run webdriver-start
            - run: npm run build
            - run: npm test
    build-and-test:
      jobs:
        - build-and-test
